-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 15:12:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`clases` (
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`coches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`coches` (
  `codigo` INT NOT NULL,
  `marca` VARCHAR(25) NULL,
  `modelo` VARCHAR(50) NULL,
  `velocidad_punta` INT NULL,
  `aceleracion` DECIMAL(10,2) NULL,
  `frenada` DECIMAL(10,2) NULL,
  `agarre` DECIMAL(10,2) NULL,
  `clase` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_coches_categorias_idx` (`clase` ASC) VISIBLE,
  CONSTRAINT `fk_coches_categorias`
    FOREIGN KEY (`clase`)
    REFERENCES `proyecto`.`clases` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`pilotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pilotos` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `apellidos` VARCHAR(100) NULL,
  `nacimiento` DATE NULL,
  `nacionalidad` VARCHAR(75) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`pruebas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pruebas` (
  `tipo` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`circuitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`circuitos` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `localizacion` VARCHAR(100) NULL,
  `longitud` DECIMAL(10,3) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`resultados` (
  `fecha` DATE NOT NULL,
  `piloto` INT NOT NULL,
  `coche` INT NOT NULL,
  `prueba` VARCHAR(50) NOT NULL,
  `circuito` INT NOT NULL,
  `mejor_tiempo` TIME NULL,
  `posicion` INT NULL,
  `recompensa` INT NULL,
  PRIMARY KEY (`fecha`, `piloto`),
  INDEX `fk_resultados_pilotos1_idx` (`piloto` ASC) VISIBLE,
  INDEX `fk_resultados_coches1_idx` (`coche` ASC) VISIBLE,
  INDEX `fk_resultados_circuitos1_idx` (`circuito` ASC) VISIBLE,
  INDEX `fk_resultados_pruebas1_idx` (`prueba` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_pilotos1`
    FOREIGN KEY (`piloto`)
    REFERENCES `proyecto`.`pilotos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultados_coches1`
    FOREIGN KEY (`coche`)
    REFERENCES `proyecto`.`coches` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultados_circuitos1`
    FOREIGN KEY (`circuito`)
    REFERENCES `proyecto`.`circuitos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultados_pruebas1`
    FOREIGN KEY (`prueba`)
    REFERENCES `proyecto`.`pruebas` (`tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
